language: java

jdk:
    - openjdk11

addons:
  sonarcloud:
    organization: fabianoveglianti ##Chiave generale
    token: 760e2914b4683e3a45dc8d12586a235a6ed57137 ##Chiave travis

script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=FabianoVeglianti_progettoMavenProva